import { useTranslation } from "react-i18next";

import type { LanguageCode } from "@/i18n";

type InsightCopy = {
  badge: string;
  title: string;
  summary: (groups: number, messages: string) => string;
  questionUnit: string;
  intentEyebrow: string;
  intentTitle: string;
  guide: string;
  cityGuides: string;
  disclaimer: string;
  topics: Array<{ label: string; description: string }>;
  intents: string[];
};

const COPY: Record<LanguageCode, InsightCopy> = {
  tr: { badge: "Anonim öğrenci ihtiyaç analizi", title: "En çok kafa karıştıran işlemler için hızlı çözüm merkezi", summary: (groups, messages) => `${groups} öğrenci topluluğundaki ${messages} kullanılabilir mesajdan, kimlik ve ham mesaj yayımlamadan çıkarılan soru başlıkları.`, questionUnit: "soru", intentEyebrow: "Soruların biçimi", intentTitle: "Öğrencinin aradığı cevap türü", guide: "Soru rehberini aç", cityGuides: "Şehir rehberlerini aç", disclaimer: "Konular birbiriyle örtüşebilir; sayılar tekil kişi sayısı değil, soru sinyali taşıyan anonim mesaj sayısıdır. Güncel hukuki ve idari bilgi için resmî kurum bağlantıları kullanılır.", topics: [ { label: "Vize, oturum ve randevu", description: "Doğru izin türü, randevu, süre ve ülkeye göre işlem sırası." }, { label: "Üniversite başvuru ve kayıt", description: "Kabul koşulları, kayıt adımları, son tarihler ve kurum doğrulama." }, { label: "İş, staj ve çalışma izni", description: "Öğrenciyken çalışma, staj bulma ve mezuniyet sonrası seçenekler." }, { label: "Belge, apostil ve denklik", description: "Belge onayı, tercüme ve tanınma süreçleri." }, { label: "Barınma, kira ve depozito", description: "Ev/yurt bulma, sözleşme, depozito ve dolandırıcılık riski." }, { label: "Banka, ödeme ve vergi numarası", description: "Hesap açma, IBAN/SWIFT, ilk ödemeler ve yerel kayıt numaraları." } ], intents: ["Hangi belgeler gerekli?", "Nasıl yapılır?", "Ne kadar tutar?", "Hangi seçenek doğru?", "Uygun muyum / kabul edilir mi?", "Ne zaman / ne kadar sürer?"] },
  en: { badge: "Anonymous student-needs analysis", title: "A quick answer center for the most confusing processes", summary: (groups, messages) => `Question themes derived from ${messages} usable messages across ${groups} student communities without publishing identities or raw messages.`, questionUnit: "questions", intentEyebrow: "Question patterns", intentTitle: "The kind of answer students are looking for", guide: "Open the question guide", cityGuides: "Open city guides", disclaimer: "Topics may overlap. Counts represent anonymous messages carrying a question signal, not unique people. Current legal and administrative information should be verified through official authorities.", topics: [ { label: "Visa, residence & appointments", description: "Permit type, appointments, timelines and country-specific process order." }, { label: "University applications & enrolment", description: "Admission requirements, enrolment steps, deadlines and institution verification." }, { label: "Jobs, internships & work rights", description: "Working while studying, internships and post-graduation options." }, { label: "Documents, apostille & recognition", description: "Certification, translation and recognition workflows." }, { label: "Housing, rent & deposits", description: "Finding housing, contracts, deposits and scam risk." }, { label: "Banking, payments & tax numbers", description: "Accounts, IBAN/SWIFT, first payments and local registration numbers." } ], intents: ["Which documents are required?", "How do I do it?", "How much does it cost?", "Which option is right?", "Am I eligible / will I be accepted?", "When / how long does it take?"] },
  de: { badge: "Anonyme Analyse studentischer Bedürfnisse", title: "Schnelle Orientierung bei den häufigsten Unsicherheiten", summary: (groups, messages) => `Fragethemen aus ${messages} nutzbaren Nachrichten in ${groups} Studierenden-Communities, ohne Identitäten oder Rohtexte zu veröffentlichen.`, questionUnit: "Fragen", intentEyebrow: "Fragemuster", intentTitle: "Welche Art von Antwort Studierende suchen", guide: "Fragen-Guide öffnen", cityGuides: "Stadt-Guides öffnen", disclaimer: "Themen können sich überschneiden. Die Zahlen stehen für anonyme Nachrichten mit Fragesignal, nicht für eindeutige Personen. Rechtliche und administrative Angaben sind bei offiziellen Stellen zu prüfen.", topics: [ { label: "Visum, Aufenthalt & Termine", description: "Genehmigungstyp, Termine, Fristen und länderspezifische Abläufe." }, { label: "Hochschulbewerbung & Einschreibung", description: "Zulassung, Einschreibung, Fristen und Verifizierung der Hochschule." }, { label: "Jobs, Praktika & Arbeitserlaubnis", description: "Arbeiten im Studium, Praktika und Optionen nach dem Abschluss." }, { label: "Dokumente, Apostille & Anerkennung", description: "Beglaubigung, Übersetzung und Anerkennungsprozesse." }, { label: "Wohnen, Miete & Kaution", description: "Wohnungssuche, Verträge, Kautionen und Betrugsrisiken." }, { label: "Bank, Zahlungen & Steuernummer", description: "Konten, IBAN/SWIFT, erste Zahlungen und lokale Registrierungen." } ], intents: ["Welche Dokumente brauche ich?", "Wie funktioniert es?", "Was kostet es?", "Welche Option passt?", "Bin ich berechtigt / werde ich zugelassen?", "Wann / wie lange dauert es?"] },
  fr: { badge: "Analyse anonyme des besoins étudiants", title: "Un centre de réponses rapides pour les démarches les plus confuses", summary: (groups, messages) => `Thèmes de questions issus de ${messages} messages exploitables dans ${groups} communautés étudiantes, sans publier d’identités ni de messages bruts.`, questionUnit: "questions", intentEyebrow: "Forme des questions", intentTitle: "Le type de réponse recherché", guide: "Ouvrir le guide des questions", cityGuides: "Ouvrir les guides de villes", disclaimer: "Les thèmes peuvent se chevaucher. Les chiffres représentent des messages anonymes comportant un signal de question, pas des personnes uniques. Les informations juridiques et administratives doivent être vérifiées auprès des sources officielles.", topics: [ { label: "Visa, séjour & rendez-vous", description: "Type d’autorisation, rendez-vous, délais et ordre des démarches." }, { label: "Candidature & inscription universitaire", description: "Conditions, inscription, échéances et vérification de l’établissement." }, { label: "Emploi, stage & droit au travail", description: "Travail étudiant, stages et options après diplôme." }, { label: "Documents, apostille & reconnaissance", description: "Certification, traduction et reconnaissance des documents." }, { label: "Logement, loyer & dépôt", description: "Recherche, contrat, dépôt et risque d’arnaque." }, { label: "Banque, paiements & numéro fiscal", description: "Compte, IBAN/SWIFT, premiers paiements et identifiants locaux." } ], intents: ["Quels documents sont nécessaires ?", "Comment faire ?", "Combien cela coûte ?", "Quelle option choisir ?", "Suis-je éligible / accepté ?", "Quand / combien de temps ?"] },
  it: { badge: "Analisi anonima dei bisogni degli studenti", title: "Risposte rapide per le procedure più confuse", summary: (groups, messages) => `Temi estratti da ${messages} messaggi utilizzabili in ${groups} community studentesche, senza pubblicare identità o messaggi grezzi.`, questionUnit: "domande", intentEyebrow: "Tipi di domanda", intentTitle: "Il tipo di risposta cercato dagli studenti", guide: "Apri la guida alle domande", cityGuides: "Apri le guide città", disclaimer: "I temi possono sovrapporsi. I conteggi indicano messaggi anonimi con un segnale di domanda, non persone uniche. Le informazioni legali e amministrative vanno verificate con fonti ufficiali.", topics: [ { label: "Visto, soggiorno & appuntamenti", description: "Tipo di permesso, appuntamenti, tempi e ordine delle procedure." }, { label: "Candidature & immatricolazione", description: "Requisiti, iscrizione, scadenze e verifica dell’istituto." }, { label: "Lavoro, stage & permessi", description: "Lavoro durante gli studi, stage e opzioni dopo la laurea." }, { label: "Documenti, apostille & riconoscimento", description: "Certificazione, traduzione e riconoscimento." }, { label: "Alloggio, affitto & deposito", description: "Ricerca casa, contratti, depositi e rischio truffe." }, { label: "Banca, pagamenti & codice fiscale", description: "Conti, IBAN/SWIFT, primi pagamenti e identificativi locali." } ], intents: ["Quali documenti servono?", "Come si fa?", "Quanto costa?", "Quale opzione è giusta?", "Sono idoneo / verrò accettato?", "Quando / quanto tempo serve?"] },
  es: { badge: "Análisis anónimo de necesidades estudiantiles", title: "Respuestas rápidas para los procesos que más dudas generan", summary: (groups, messages) => `Temas derivados de ${messages} mensajes utilizables en ${groups} comunidades estudiantiles, sin publicar identidades ni mensajes brutos.`, questionUnit: "preguntas", intentEyebrow: "Patrones de preguntas", intentTitle: "El tipo de respuesta que busca el estudiante", guide: "Abrir guía de preguntas", cityGuides: "Abrir guías de ciudades", disclaimer: "Los temas pueden solaparse. Las cifras representan mensajes anónimos con señales de pregunta, no personas únicas. La información legal y administrativa debe verificarse en fuentes oficiales.", topics: [ { label: "Visado, residencia & citas", description: "Tipo de permiso, citas, plazos y orden del proceso por país." }, { label: "Solicitud & matrícula universitaria", description: "Requisitos, matrícula, fechas y verificación de instituciones." }, { label: "Trabajo, prácticas & permisos", description: "Trabajar mientras estudias, prácticas y opciones tras graduarte." }, { label: "Documentos, apostilla & reconocimiento", description: "Certificación, traducción y reconocimiento documental." }, { label: "Alojamiento, alquiler & depósito", description: "Búsqueda, contratos, depósitos y riesgo de fraude." }, { label: "Banco, pagos & número fiscal", description: "Cuentas, IBAN/SWIFT, primeros pagos y registros locales." } ], intents: ["¿Qué documentos necesito?", "¿Cómo se hace?", "¿Cuánto cuesta?", "¿Qué opción es correcta?", "¿Soy elegible / me aceptarán?", "¿Cuándo / cuánto tarda?"] },
  ar: { badge: "تحليل مجهول لاحتياجات الطلاب", title: "مركز إجابات سريع لأكثر الإجراءات إرباكاً", summary: (groups, messages) => `موضوعات أسئلة مستخلصة من ${messages} رسالة قابلة للتحليل ضمن ${groups} مجتمعاً طلابياً دون نشر الهوية أو الرسائل الخام.`, questionUnit: "سؤال", intentEyebrow: "أنماط الأسئلة", intentTitle: "نوع الإجابة التي يبحث عنها الطالب", guide: "فتح دليل الأسئلة", cityGuides: "فتح أدلة المدن", disclaimer: "قد تتداخل الموضوعات. الأرقام تمثل رسائل مجهولة تحمل إشارة سؤال وليست عدد أشخاص فريدين. يجب التحقق من المعلومات القانونية والإدارية لدى الجهات الرسمية.", topics: [ { label: "التأشيرة والإقامة والمواعيد", description: "نوع الإذن والمواعيد والمدد وترتيب الإجراءات حسب الدولة." }, { label: "التقديم والتسجيل الجامعي", description: "شروط القبول والتسجيل والمواعيد والتحقق من المؤسسة." }, { label: "العمل والتدريب وتصاريح العمل", description: "العمل أثناء الدراسة والتدريب والخيارات بعد التخرج." }, { label: "المستندات والأبوستيل والاعتراف", description: "التصديق والترجمة والاعتراف بالمستندات." }, { label: "السكن والإيجار والوديعة", description: "البحث عن السكن والعقود والودائع ومخاطر الاحتيال." }, { label: "البنوك والمدفوعات والرقم الضريبي", description: "الحسابات وIBAN/SWIFT والمدفوعات الأولى وأرقام التسجيل." } ], intents: ["ما المستندات المطلوبة؟", "كيف يتم ذلك؟", "كم التكلفة؟", "ما الخيار المناسب؟", "هل أنا مؤهل / سأُقبل؟", "متى / كم يستغرق؟"] },
  ru: { badge: "Анонимный анализ потребностей студентов", title: "Быстрые ответы на самые запутанные процессы", summary: (groups, messages) => `Темы вопросов из ${messages} пригодных сообщений в ${groups} студенческих сообществах без публикации личностей и исходных сообщений.`, questionUnit: "вопросов", intentEyebrow: "Формат вопросов", intentTitle: "Какой ответ ищут студенты", guide: "Открыть гид по вопросам", cityGuides: "Открыть гиды по городам", disclaimer: "Темы могут пересекаться. Числа отражают анонимные сообщения с вопросительным сигналом, а не уникальных людей. Юридическую и административную информацию следует проверять по официальным источникам.", topics: [ { label: "Виза, ВНЖ & записи", description: "Тип разрешения, запись, сроки и порядок действий по стране." }, { label: "Поступление & регистрация", description: "Требования, этапы регистрации, дедлайны и проверка вуза." }, { label: "Работа, стажировки & разрешения", description: "Работа во время учёбы, стажировки и варианты после выпуска." }, { label: "Документы, апостиль & признание", description: "Заверение, перевод и признание документов." }, { label: "Жильё, аренда & депозит", description: "Поиск жилья, договоры, депозиты и риск мошенничества." }, { label: "Банк, платежи & налоговый номер", description: "Счета, IBAN/SWIFT, первые платежи и местные номера." } ], intents: ["Какие документы нужны?", "Как это сделать?", "Сколько это стоит?", "Какой вариант выбрать?", "Подхожу ли я / примут ли меня?", "Когда / сколько времени?"] },
  zh: { badge: "匿名学生需求分析", title: "针对最容易困惑流程的快速解答中心", summary: (groups, messages) => `基于 ${groups} 个学生社区中的 ${messages} 条可用消息提炼问题主题，不公开身份或原始消息。`, questionUnit: "个问题", intentEyebrow: "问题类型", intentTitle: "学生正在寻找的答案类型", guide: "打开问题指南", cityGuides: "打开城市指南", disclaimer: "主题可能重叠。数字代表带有问题信号的匿名消息，并非独立用户人数。法律和行政信息应通过官方机构核实。", topics: [ { label: "签证、居留与预约", description: "许可类型、预约、时限和各国办理顺序。" }, { label: "大学申请与注册", description: "录取要求、注册步骤、截止日期和院校核验。" }, { label: "工作、实习与工作许可", description: "学习期间工作、实习及毕业后选择。" }, { label: "文件、海牙认证与认可", description: "文件认证、翻译和认可流程。" }, { label: "住宿、租金与押金", description: "找房、合同、押金和诈骗风险。" }, { label: "银行、支付与税号", description: "开户、IBAN/SWIFT、初始支付和本地登记号码。" } ], intents: ["需要哪些文件？", "如何办理？", "费用多少？", "哪个选项合适？", "我符合条件 / 会被录取吗？", "什么时候 / 需要多久？"] },
};

export function usePortalInsightsCopy() {
  const { i18n } = useTranslation();
  const raw = i18n.resolvedLanguage || i18n.language || "tr";
  const normalized = raw.split("-")[0] as LanguageCode;
  const language: LanguageCode = normalized in COPY ? normalized : "tr";
  return { copy: COPY[language], locale: language === "zh" ? "zh-CN" : language };
}
