import { useTranslation } from "react-i18next";

import type { LanguageCode } from "@/i18n";

type PublicPortalCopy = {
  hero: {
    title: string;
    accent: string;
    subtitle: string;
    discover: string;
    continue: string;
    privateDocs: string;
    officialSources: string;
    deadlines: string;
    overview: string;
    overviewTitle: string;
    nextAction: string;
    nextActionTitle: string;
    nextActionDesc: string;
    applications: string;
    documents: string;
    life: string;
    provenance: string;
  };
  journey: {
    badge: string;
    title: string;
    subtitle: string;
    descriptions: Record<string, string>;
    workspaceTitle: string;
    workspaceDesc: string;
    openWorkspace: string;
  };
  discovery: { eyebrow: string; title: string; subtitle: string };
  life: {
    badge: string;
    title: string;
    subtitle: string;
    workspace: string;
    groups: Array<{ title: string; description: string; items: string[] }>;
    institution: string;
    institutionDesc: string;
    moderation: string;
    moderationDesc: string;
    privateFiles: string;
    privateFilesDesc: string;
  };
  commerce: {
    badge: string;
    title: string;
    description: string;
    contact: string;
    plans: string;
    plansTitle: string;
    plansDesc: string;
    featured: string;
    month: string;
    year: string;
    creditsIncluded: string;
    securePending: string;
    creditPacks: string;
    compareCredits: string;
    purchaseSoon: string;
    planDescriptions: Record<string, string>;
    planFeatures: Record<string, string[]>;
  };
};

const COPY: Record<LanguageCode, PublicPortalCopy> = {
  tr: {
    hero: { title: "Yurt dışı eğitim yolculuğun,", accent: "tek çalışma alanında.", subtitle: "Program keşfinden başvuru ve belge takibine, vizeden konaklama ve varış planına kadar tüm süreci tek öğrenci çalışma alanında yönet.", discover: "Programları keşfet", continue: "Yolculuğuma devam et", privateDocs: "Özel öğrenci belgeleri", officialSources: "Resmî kaynak ayrımı", deadlines: "Son tarih odaklı çalışma alanı", overview: "Yolculuk özeti", overviewTitle: "Sıradaki adımı gör, sonra detaylara in", nextAction: "Sıradaki en önemli adım", nextActionTitle: "İlk hedef kurumlarını kısa listeye ekle", nextActionDesc: "Portal, bütün menüyü değil o anda ilerlemeyi sağlayacak en önemli adımı öne çıkarır.", applications: "Başvurular", documents: "Belgeler", life: "Öğrenci yaşamı", provenance: "Kaynak türü ve güncellik görünür" },
    journey: { badge: "Öğrenci yolculuğu", title: "Başvuruyu değil, tüm yolculuğu yönet", subtitle: "Her aşama bir sonrakine bağlanır. Belgeler son tarihlere, son tarihler başvurulara; başvurular da vize ve yerleşme görevlerine dönüşür.", descriptions: { discover: "Ülke, şehir, kurum ve akademik alanları karşılaştır.", shortlist: "Gerçekten değerlendirmek istediğin seçenekleri tek yerde tut.", documents: "Başvuru dosyanı özel belge merkezinde düzenle.", apply: "Son tarih, durum ve eksik gereksinimleri takip et.", visa: "Vize, finans ve resmî hazırlıkları planla.", housing: "Konaklama ve yerleşme seçeneklerini güvenle değerlendir.", arrival: "İlk hafta ve yerleşme görevlerini tamamla.", offer: "Teklifleri ve kabul kararını takip et." }, workspaceTitle: "Çalışma alanın hesabınla birlikte ilerler.", workspaceDesc: "Başvuru, görev ve özel belgelerini tek yerde tut.", openWorkspace: "Workspace’i aç" },
    discovery: { eyebrow: "Program keşfi", title: "Önce seçenekleri bul, sonra çalışma alanına taşı", subtitle: "Kurum ve akademik alan verisini keşif amacıyla kullan; kesin program, kabul koşulu ve ücretler için resmî kurum kaynağını esas al." },
    life: { badge: "Yurt dışında yaşam", title: "Öğrenci yaşamı, ama ana iş akışını bozmadan", subtitle: "Topluluk ve marketplace ana ürün değil; eğitim yolculuğunu tamamlayan güvenlik odaklı yardımcı modüllerdir.", workspace: "Workspace’e git", groups: [ { title: "Konaklama", description: "Yurt, ev, oda ve ev arkadaşı seçeneklerini daha güvenli değerlendir.", items: ["Yurt", "Ev / oda", "Ev arkadaşı"] }, { title: "Finans & iş", description: "Burs, öğrenci işi ve günlük bütçe kararlarını tek başlıkta yönet.", items: ["Burs", "İş & staj", "Finans"] }, { title: "Topluluk", description: "Şehir, okul ve bölüm bağlamında moderasyonlu öğrenci ağına eriş.", items: ["Topluluklar", "Öğrenci grupları", "Yerel bağlantılar"] }, { title: "Günlük yaşam", description: "Sağlık, ulaşım, bağlantı ve ikinci el ihtiyaçlarını tamamlayıcı modül olarak kullan.", items: ["Sağlık", "Ulaşım", "Bağlantı & pazar"] } ], institution: "Kurum bilgisi", institutionDesc: "Resmî kaynak ile akademik sinyal ayrı etiketlenir.", moderation: "Topluluk ilanları", moderationDesc: "Moderasyon ve hesap doğrulama süreçleri görünür tutulur.", privateFiles: "Özel dosyalar", privateFilesDesc: "Başvuru belgeleri herkese açık URL ile paylaşılmaz." },
    commerce: { badge: "Güvenli ödeme durumu", title: "Portal içerikleri açık, ödeme işlemleri kontrollü biçimde beklemede", description: "Bu üretim sürümü statik web barındırma üzerinde çalıştığı için kartlı ödeme ve ödeme hesabı işlemleri burada başlatılmaz. Böylece başarısız checkout bağlantıları gösterilmez ve gizli anahtarlar tarayıcıya taşınmaz.", contact: "Üyelik ve ödeme hakkında bilgi al", plans: "Üyelik planları", plansTitle: "Yolculuğuna uygun planı incele", plansDesc: "Planlar ve kredi paketleri şeffaf biçimde gösterilir. Satın alma, güvenli ödeme backend’i production’a alındığında etkinleşir.", featured: "En çok tercih edilen", month: "ay", year: "yıl", creditsIncluded: "kredi dahil", securePending: "Güvenli ödeme hazırlanıyor", creditPacks: "İlan kredileri", compareCredits: "Kredi paketlerini karşılaştır", purchaseSoon: "Satın alma yakında", planDescriptions: { basic: "Temel portal ve doğrulama araçlarına erişim.", plus: "Başvuru ve yerleşme sürecini daha kapsamlı yönet.", pro: "Yoğun kullanan öğrenciler ve ilan verenler için gelişmiş araçlar." }, planFeatures: { basic: ["Portal erişimi", "10 başlangıç kredisi", "Kurum ve program keşfi", "Favoriler", "Doğrulama başvurusu"], plus: ["Basic özellikleri", "30 kredi", "Son tarih ve belge planlayıcı", "Doğrulanmış topluluklar", "Kişiselleştirilmiş bildirimler"], pro: ["Plus özellikleri", "80 kredi", "Gelişmiş program eşleştirme", "Özel belge çalışma alanı", "Öncelikli moderasyon"] } },
  },
  en: {
    hero: { title: "Your study-abroad journey,", accent: "in one workspace.", subtitle: "Manage program discovery, applications, private documents, visa preparation, housing and arrival planning in one student workspace.", discover: "Discover programs", continue: "Continue my journey", privateDocs: "Private student documents", officialSources: "Official-source distinction", deadlines: "Deadline-focused workspace", overview: "Journey overview", overviewTitle: "See the next step, then go deeper", nextAction: "Next best action", nextActionTitle: "Add your first target institutions to a shortlist", nextActionDesc: "The portal prioritizes the action that moves you forward instead of showing every menu at once.", applications: "Applications", documents: "Documents", life: "Student life", provenance: "Source type and freshness stay visible" },
    journey: { badge: "Student journey", title: "Manage the whole journey, not just the application", subtitle: "Each stage connects to the next. Documents feed deadlines, deadlines feed applications, and applications lead to visa and settlement tasks.", descriptions: { discover: "Compare countries, cities, institutions and academic fields.", shortlist: "Keep the options you genuinely want to evaluate in one place.", documents: "Organize application files in your private document center.", apply: "Track deadlines, status and missing requirements.", offer: "Track offers and admission decisions.", visa: "Plan visa, finance and official preparation.", housing: "Evaluate housing and settlement options more safely.", arrival: "Complete first-week and arrival tasks." }, workspaceTitle: "Your workspace progresses with your account.", workspaceDesc: "Keep applications, tasks and private documents connected.", openWorkspace: "Open workspace" },
    discovery: { eyebrow: "Program discovery", title: "Find options first, then move them into your workspace", subtitle: "Use institution and academic data for discovery; rely on the institution’s official source for exact programs, admission requirements and fees." },
    life: { badge: "Life abroad", title: "Student life without disrupting the core workflow", subtitle: "Community and marketplace are supporting modules that complement the education journey rather than replacing it.", workspace: "Go to workspace", groups: [ { title: "Housing", description: "Evaluate dorms, homes, rooms and roommate options more safely.", items: ["Dorms", "Homes / rooms", "Roommates"] }, { title: "Finance & work", description: "Manage scholarships, student work and everyday budget decisions together.", items: ["Scholarships", "Jobs & internships", "Finance"] }, { title: "Community", description: "Access moderated student networks by city, school and program context.", items: ["Communities", "Student groups", "Local connections"] }, { title: "Daily life", description: "Use health, transport, connectivity and resale tools as supporting modules.", items: ["Health", "Transport", "Connectivity & market"] } ], institution: "Institution data", institutionDesc: "Official sources and academic signals are labelled separately.", moderation: "Community listings", moderationDesc: "Moderation and account-verification states remain visible.", privateFiles: "Private files", privateFilesDesc: "Application documents are never shared through a public URL." },
    commerce: { badge: "Secure payment status", title: "Portal content is available; payments are safely paused", description: "This production site is statically hosted, so card payments and payout-account actions are not started here. This prevents broken checkout links and keeps secret keys out of the browser.", contact: "Ask about membership and payments", plans: "Membership plans", plansTitle: "Review the plan that fits your journey", plansDesc: "Plans and credit packs remain transparent. Purchasing will activate when the secure payment backend is live.", featured: "Most popular", month: "month", year: "year", creditsIncluded: "credits included", securePending: "Secure payment being prepared", creditPacks: "Listing credits", compareCredits: "Compare credit packs", purchaseSoon: "Purchasing coming soon", planDescriptions: { basic: "Access core portal and verification tools.", plus: "Manage applications and settlement with more planning tools.", pro: "Advanced tools for power users and verified listers." }, planFeatures: { basic: ["Portal access", "10 starter credits", "Institution and program discovery", "Saved items", "Verification request"], plus: ["Everything in Basic", "30 credits", "Deadline and document planner", "Verified communities", "Personalized notifications"], pro: ["Everything in Plus", "80 credits", "Advanced program matching", "Private document workspace", "Priority moderation"] } },
  },
  de: {
    hero: { title: "Dein Weg zum Auslandsstudium,", accent: "in einem Arbeitsbereich.", subtitle: "Verwalte Programmsuche, Bewerbungen, private Dokumente, Visum, Wohnen und Ankunft in einem Student Workspace.", discover: "Programme entdecken", continue: "Meine Reise fortsetzen", privateDocs: "Private Studentendokumente", officialSources: "Offizielle Quellen getrennt", deadlines: "Fristen im Fokus", overview: "Reiseübersicht", overviewTitle: "Den nächsten Schritt sehen und dann vertiefen", nextAction: "Nächster wichtiger Schritt", nextActionTitle: "Erste Zielhochschulen zur Auswahl hinzufügen", nextActionDesc: "Das Portal priorisiert die Handlung, die dich voranbringt, statt alle Menüs gleichzeitig zu zeigen.", applications: "Bewerbungen", documents: "Dokumente", life: "Studentenleben", provenance: "Quellentyp und Aktualität bleiben sichtbar" },
    journey: { badge: "Student Journey", title: "Die ganze Reise verwalten, nicht nur die Bewerbung", subtitle: "Jede Phase baut auf der nächsten auf: Dokumente, Fristen, Bewerbungen, Visum und Ankunft.", descriptions: { discover: "Länder, Städte, Hochschulen und Fachgebiete vergleichen.", shortlist: "Relevante Optionen an einem Ort sammeln.", documents: "Bewerbungsunterlagen privat organisieren.", apply: "Fristen, Status und fehlende Anforderungen verfolgen.", offer: "Zulassungen und Entscheidungen verfolgen.", visa: "Visum, Finanzierung und offizielle Vorbereitung planen.", housing: "Wohn- und Ankunftsoptionen sicherer bewerten.", arrival: "Aufgaben für Ankunft und erste Woche erledigen." }, workspaceTitle: "Dein Arbeitsbereich wächst mit deinem Konto.", workspaceDesc: "Bewerbungen, Aufgaben und private Dokumente verbunden halten.", openWorkspace: "Workspace öffnen" },
    discovery: { eyebrow: "Programmsuche", title: "Optionen finden und anschließend in den Workspace übernehmen", subtitle: "Nutze Hochschul- und Forschungsdaten zur Orientierung; für Programme, Zulassung und Gebühren gilt die offizielle Hochschulquelle." },
    life: { badge: "Leben im Ausland", title: "Studentenleben ohne den Kernprozess zu stören", subtitle: "Community und Marktplatz ergänzen den Bildungsweg als unterstützende Module.", workspace: "Zum Workspace", groups: [ { title: "Wohnen", description: "Wohnheim-, Zimmer- und Mitbewohneroptionen sicherer vergleichen.", items: ["Wohnheim", "Wohnung / Zimmer", "Mitbewohner"] }, { title: "Finanzen & Arbeit", description: "Stipendien, Studentenjobs und Budget gemeinsam planen.", items: ["Stipendien", "Jobs & Praktika", "Finanzen"] }, { title: "Community", description: "Moderierte Netzwerke nach Stadt, Hochschule und Programm nutzen.", items: ["Communities", "Studentengruppen", "Lokale Kontakte"] }, { title: "Alltag", description: "Gesundheit, Verkehr, Internet und Secondhand als Ergänzung nutzen.", items: ["Gesundheit", "Verkehr", "Internet & Markt"] } ], institution: "Hochschuldaten", institutionDesc: "Offizielle Quellen und akademische Signale werden getrennt markiert.", moderation: "Community-Anzeigen", moderationDesc: "Moderation und Verifizierung bleiben sichtbar.", privateFiles: "Private Dateien", privateFilesDesc: "Bewerbungsdokumente erhalten keine öffentliche URL." },
    commerce: { badge: "Sicherer Zahlungsstatus", title: "Portal verfügbar; Zahlungen sicher pausiert", description: "Die Produktionsseite ist statisch gehostet. Karten- und Auszahlungsvorgänge werden daher nicht gestartet; geheime Schlüssel bleiben außerhalb des Browsers.", contact: "Zu Mitgliedschaft und Zahlung fragen", plans: "Mitgliedschaften", plansTitle: "Passenden Plan ansehen", plansDesc: "Pläne und Credits bleiben transparent; Kauf wird mit dem sicheren Backend aktiviert.", featured: "Beliebt", month: "Monat", year: "Jahr", creditsIncluded: "Credits inklusive", securePending: "Sichere Zahlung wird vorbereitet", creditPacks: "Anzeigen-Credits", compareCredits: "Credit-Pakete vergleichen", purchaseSoon: "Kauf folgt", planDescriptions: { basic: "Kernportal und Verifizierung.", plus: "Mehr Planung für Bewerbung und Ankunft.", pro: "Erweiterte Werkzeuge für intensive Nutzung." }, planFeatures: { basic: ["Portalzugang", "10 Start-Credits", "Programm- und Hochschulsuche", "Gespeicherte Inhalte", "Verifizierung"], plus: ["Alles aus Basic", "30 Credits", "Fristen- und Dokumentplanung", "Verifizierte Communities", "Personalisierte Hinweise"], pro: ["Alles aus Plus", "80 Credits", "Erweitertes Matching", "Privater Dokumentbereich", "Priorisierte Moderation"] } },
  },
  fr: {
    hero: { title: "Votre parcours d’études à l’étranger,", accent: "dans un seul espace.", subtitle: "Gérez recherche de programmes, candidatures, documents privés, visa, logement et arrivée dans un espace étudiant unique.", discover: "Découvrir les programmes", continue: "Continuer mon parcours", privateDocs: "Documents étudiants privés", officialSources: "Sources officielles distinguées", deadlines: "Espace axé sur les échéances", overview: "Vue du parcours", overviewTitle: "Voir la prochaine étape puis approfondir", nextAction: "Prochaine action prioritaire", nextActionTitle: "Ajoutez vos premiers établissements cibles", nextActionDesc: "Le portail met en avant l’action qui fait avancer votre dossier plutôt que tous les menus à la fois.", applications: "Candidatures", documents: "Documents", life: "Vie étudiante", provenance: "Type de source et fraîcheur visibles" },
    journey: { badge: "Parcours étudiant", title: "Gérez tout le parcours, pas seulement la candidature", subtitle: "Chaque étape alimente la suivante: documents, échéances, candidatures, visa et installation.", descriptions: { discover: "Comparer pays, villes, établissements et domaines.", shortlist: "Conserver les options réellement pertinentes.", documents: "Organiser les pièces de candidature dans un espace privé.", apply: "Suivre échéances, statut et éléments manquants.", offer: "Suivre offres et décisions d’admission.", visa: "Planifier visa, financement et démarches officielles.", housing: "Évaluer logement et installation plus sereinement.", arrival: "Terminer les tâches d’arrivée et de première semaine." }, workspaceTitle: "Votre espace évolue avec votre compte.", workspaceDesc: "Reliez candidatures, tâches et documents privés.", openWorkspace: "Ouvrir l’espace" },
    discovery: { eyebrow: "Découverte de programmes", title: "Trouvez les options puis transférez-les dans votre espace", subtitle: "Utilisez les données institutionnelles pour explorer; pour les programmes, admissions et frais, référez-vous à la source officielle." },
    life: { badge: "Vie à l’étranger", title: "La vie étudiante sans perturber le parcours principal", subtitle: "Communauté et marketplace complètent le parcours sans devenir le cœur du produit.", workspace: "Aller à l’espace", groups: [ { title: "Logement", description: "Évaluer résidences, chambres et colocations plus sûrement.", items: ["Résidences", "Logement / chambre", "Colocation"] }, { title: "Finance & travail", description: "Regrouper bourses, emploi étudiant et budget.", items: ["Bourses", "Jobs & stages", "Finance"] }, { title: "Communauté", description: "Réseaux modérés par ville, établissement et programme.", items: ["Communautés", "Groupes étudiants", "Réseau local"] }, { title: "Vie quotidienne", description: "Santé, transport, connectivité et seconde main comme modules d’appoint.", items: ["Santé", "Transport", "Connexion & marché"] } ], institution: "Données établissement", institutionDesc: "Sources officielles et signaux académiques sont séparés.", moderation: "Annonces communautaires", moderationDesc: "Modération et vérification restent visibles.", privateFiles: "Fichiers privés", privateFilesDesc: "Les documents de candidature ne sont jamais publiés via une URL publique." },
    commerce: { badge: "État du paiement sécurisé", title: "Le portail reste accessible; les paiements sont suspendus en sécurité", description: "Le site de production est hébergé statiquement; les paiements par carte et comptes de versement ne sont donc pas démarrés ici, et aucun secret n’est exposé au navigateur.", contact: "Demander des informations sur l’abonnement", plans: "Abonnements", plansTitle: "Consulter le plan adapté", plansDesc: "Plans et crédits restent transparents; l’achat sera activé avec le backend de paiement sécurisé.", featured: "Le plus choisi", month: "mois", year: "an", creditsIncluded: "crédits inclus", securePending: "Paiement sécurisé en préparation", creditPacks: "Crédits d’annonce", compareCredits: "Comparer les packs", purchaseSoon: "Achat bientôt disponible", planDescriptions: { basic: "Outils essentiels du portail et vérification.", plus: "Planification plus complète des candidatures et de l’installation.", pro: "Outils avancés pour les utilisateurs intensifs." }, planFeatures: { basic: ["Accès portail", "10 crédits de départ", "Recherche programmes et établissements", "Éléments enregistrés", "Vérification"], plus: ["Tout Basic", "30 crédits", "Planificateur échéances et documents", "Communautés vérifiées", "Notifications personnalisées"], pro: ["Tout Plus", "80 crédits", "Matching avancé", "Espace documentaire privé", "Modération prioritaire"] } },
  },
  it: {
    hero: { title: "Il tuo percorso di studio all’estero,", accent: "in un unico workspace.", subtitle: "Gestisci ricerca programmi, candidature, documenti privati, visto, alloggio e arrivo in un solo spazio studente.", discover: "Scopri i programmi", continue: "Continua il mio percorso", privateDocs: "Documenti studente privati", officialSources: "Fonti ufficiali distinte", deadlines: "Workspace orientato alle scadenze", overview: "Panoramica percorso", overviewTitle: "Vedi il prossimo passo, poi entra nei dettagli", nextAction: "Prossima azione prioritaria", nextActionTitle: "Aggiungi i primi istituti target", nextActionDesc: "Il portale mette in evidenza l’azione che fa avanzare il percorso invece di mostrare tutto insieme.", applications: "Candidature", documents: "Documenti", life: "Vita studentesca", provenance: "Fonte e aggiornamento sempre visibili" },
    journey: { badge: "Percorso studente", title: "Gestisci tutto il percorso, non solo la candidatura", subtitle: "Ogni fase alimenta la successiva: documenti, scadenze, candidature, visto e sistemazione.", descriptions: { discover: "Confronta paesi, città, istituti e aree accademiche.", shortlist: "Conserva in un solo posto le opzioni davvero rilevanti.", documents: "Organizza i file di candidatura nello spazio privato.", apply: "Segui scadenze, stato e requisiti mancanti.", offer: "Segui offerte e decisioni di ammissione.", visa: "Pianifica visto, finanze e procedure ufficiali.", housing: "Valuta alloggio e sistemazione in modo più sicuro.", arrival: "Completa le attività di arrivo e prima settimana." }, workspaceTitle: "Il workspace cresce con il tuo account.", workspaceDesc: "Tieni collegati candidature, attività e documenti privati.", openWorkspace: "Apri workspace" },
    discovery: { eyebrow: "Scoperta programmi", title: "Trova le opzioni e portale nel workspace", subtitle: "Usa i dati accademici per esplorare; per programmi, ammissione e costi vale la fonte ufficiale dell’istituto." },
    life: { badge: "Vita all’estero", title: "Vita studentesca senza interrompere il flusso principale", subtitle: "Community e marketplace completano il percorso come moduli di supporto.", workspace: "Vai al workspace", groups: [ { title: "Alloggio", description: "Valuta studentati, case, stanze e coinquilini in modo più sicuro.", items: ["Studentati", "Casa / stanza", "Coinquilini"] }, { title: "Finanza & lavoro", description: "Gestisci borse, lavoro studentesco e budget insieme.", items: ["Borse", "Lavoro & stage", "Finanza"] }, { title: "Community", description: "Reti moderate per città, istituto e programma.", items: ["Community", "Gruppi studenti", "Contatti locali"] }, { title: "Vita quotidiana", description: "Salute, trasporto, connettività e usato come moduli di supporto.", items: ["Salute", "Trasporto", "Connessione & mercato"] } ], institution: "Dati istituto", institutionDesc: "Fonti ufficiali e segnali accademici sono distinti.", moderation: "Annunci community", moderationDesc: "Moderazione e verifica restano visibili.", privateFiles: "File privati", privateFilesDesc: "I documenti di candidatura non ricevono URL pubblici." },
    commerce: { badge: "Stato pagamento sicuro", title: "Il portale è disponibile; i pagamenti sono sospesi in sicurezza", description: "Il sito production è ospitato staticamente, quindi pagamenti e payout non vengono avviati qui e nessuna chiave segreta viene esposta al browser.", contact: "Informazioni su abbonamento e pagamenti", plans: "Piani", plansTitle: "Consulta il piano adatto", plansDesc: "Piani e crediti restano trasparenti; l’acquisto si attiverà con il backend sicuro.", featured: "Più scelto", month: "mese", year: "anno", creditsIncluded: "crediti inclusi", securePending: "Pagamento sicuro in preparazione", creditPacks: "Crediti annunci", compareCredits: "Confronta i pacchetti", purchaseSoon: "Acquisto presto disponibile", planDescriptions: { basic: "Strumenti essenziali del portale e verifica.", plus: "Più strumenti per candidature e sistemazione.", pro: "Strumenti avanzati per utenti intensivi." }, planFeatures: { basic: ["Accesso portale", "10 crediti iniziali", "Ricerca programmi e istituti", "Preferiti", "Verifica"], plus: ["Tutto Basic", "30 crediti", "Planner scadenze e documenti", "Community verificate", "Notifiche personalizzate"], pro: ["Tutto Plus", "80 crediti", "Matching avanzato", "Workspace documenti privato", "Moderazione prioritaria"] } },
  },
  es: {
    hero: { title: "Tu recorrido de estudios en el extranjero,", accent: "en un solo espacio.", subtitle: "Gestiona búsqueda de programas, solicitudes, documentos privados, visado, alojamiento y llegada en un único workspace.", discover: "Descubrir programas", continue: "Continuar mi recorrido", privateDocs: "Documentos privados", officialSources: "Fuentes oficiales diferenciadas", deadlines: "Espacio centrado en fechas límite", overview: "Resumen del recorrido", overviewTitle: "Ve el siguiente paso y luego profundiza", nextAction: "Próxima acción prioritaria", nextActionTitle: "Añade tus primeras instituciones objetivo", nextActionDesc: "El portal destaca la acción que te hace avanzar en lugar de mostrar todos los menús a la vez.", applications: "Solicitudes", documents: "Documentos", life: "Vida estudiantil", provenance: "Tipo de fuente y actualización visibles" },
    journey: { badge: "Recorrido del estudiante", title: "Gestiona todo el recorrido, no solo la solicitud", subtitle: "Cada etapa alimenta la siguiente: documentos, fechas, solicitudes, visado y llegada.", descriptions: { discover: "Compara países, ciudades, instituciones y áreas.", shortlist: "Guarda las opciones que realmente quieres evaluar.", documents: "Organiza documentos de solicitud en tu espacio privado.", apply: "Sigue fechas límite, estado y requisitos pendientes.", offer: "Sigue ofertas y decisiones de admisión.", visa: "Planifica visado, finanzas y trámites oficiales.", housing: "Evalúa alojamiento y llegada de forma más segura.", arrival: "Completa tareas de llegada y primera semana." }, workspaceTitle: "Tu workspace avanza contigo.", workspaceDesc: "Conecta solicitudes, tareas y documentos privados.", openWorkspace: "Abrir workspace" },
    discovery: { eyebrow: "Descubrimiento de programas", title: "Encuentra opciones y llévalas a tu workspace", subtitle: "Usa datos académicos para explorar; para programas, requisitos y tasas, consulta siempre la fuente oficial." },
    life: { badge: "Vida en el extranjero", title: "Vida estudiantil sin romper el flujo principal", subtitle: "Comunidad y marketplace complementan el recorrido como módulos de apoyo.", workspace: "Ir al workspace", groups: [ { title: "Alojamiento", description: "Evalúa residencias, casas, habitaciones y compañeros de forma más segura.", items: ["Residencias", "Casa / habitación", "Compañeros"] }, { title: "Finanzas & trabajo", description: "Gestiona becas, empleo estudiantil y presupuesto juntos.", items: ["Becas", "Trabajo & prácticas", "Finanzas"] }, { title: "Comunidad", description: "Redes moderadas por ciudad, institución y programa.", items: ["Comunidades", "Grupos", "Conexiones locales"] }, { title: "Vida diaria", description: "Salud, transporte, conectividad y segunda mano como apoyo.", items: ["Salud", "Transporte", "Conexión & mercado"] } ], institution: "Datos de institución", institutionDesc: "Fuentes oficiales y señales académicas se etiquetan por separado.", moderation: "Anuncios comunitarios", moderationDesc: "Moderación y verificación permanecen visibles.", privateFiles: "Archivos privados", privateFilesDesc: "Los documentos de solicitud no se comparten con URL pública." },
    commerce: { badge: "Estado del pago seguro", title: "El portal está disponible; los pagos están pausados de forma segura", description: "La producción usa hosting estático; los pagos y cuentas de cobro no se inician aquí, evitando enlaces rotos y secretos en el navegador.", contact: "Información sobre membresía y pagos", plans: "Planes", plansTitle: "Consulta el plan adecuado", plansDesc: "Planes y créditos son transparentes; la compra se activará con el backend seguro.", featured: "Más elegido", month: "mes", year: "año", creditsIncluded: "créditos incluidos", securePending: "Pago seguro en preparación", creditPacks: "Créditos de anuncios", compareCredits: "Comparar paquetes", purchaseSoon: "Compra próximamente", planDescriptions: { basic: "Herramientas esenciales y verificación.", plus: "Más planificación para solicitudes y llegada.", pro: "Herramientas avanzadas para uso intensivo." }, planFeatures: { basic: ["Acceso portal", "10 créditos iniciales", "Búsqueda de programas", "Guardados", "Verificación"], plus: ["Todo Basic", "30 créditos", "Planificador de fechas y documentos", "Comunidades verificadas", "Notificaciones personalizadas"], pro: ["Todo Plus", "80 créditos", "Matching avanzado", "Workspace de documentos privado", "Moderación prioritaria"] } },
  },
  ar: {
    hero: { title: "رحلة الدراسة في الخارج،", accent: "في مساحة عمل واحدة.", subtitle: "أدر اكتشاف البرامج والطلبات والمستندات الخاصة والتأشيرة والسكن وخطة الوصول في مساحة واحدة للطالب.", discover: "استكشف البرامج", continue: "متابعة رحلتي", privateDocs: "مستندات طالب خاصة", officialSources: "تمييز المصادر الرسمية", deadlines: "مساحة تركز على المواعيد", overview: "نظرة عامة", overviewTitle: "شاهد الخطوة التالية ثم انتقل للتفاصيل", nextAction: "الخطوة الأهم التالية", nextActionTitle: "أضف أول المؤسسات المستهدفة إلى قائمتك", nextActionDesc: "يعرض البوابة الإجراء الذي يدفعك للأمام بدلاً من إظهار جميع القوائم دفعة واحدة.", applications: "الطلبات", documents: "المستندات", life: "حياة الطالب", provenance: "نوع المصدر وحداثته يظلان ظاهرين" },
    journey: { badge: "رحلة الطالب", title: "أدر الرحلة كاملة وليس الطلب فقط", subtitle: "كل مرحلة تقود إلى التالية: مستندات، مواعيد، طلبات، تأشيرة ثم الوصول.", descriptions: { discover: "قارن الدول والمدن والمؤسسات والمجالات الأكاديمية.", shortlist: "احتفظ بالخيارات التي تريد تقييمها فعلياً.", documents: "نظّم ملفات الطلب في مركز المستندات الخاص.", apply: "تابع المواعيد والحالة والمتطلبات الناقصة.", offer: "تابع العروض وقرارات القبول.", visa: "خطط للتأشيرة والتمويل والإجراءات الرسمية.", housing: "قيّم خيارات السكن والاستقرار بأمان أكبر.", arrival: "أكمل مهام الوصول والأسبوع الأول." }, workspaceTitle: "مساحة عملك تتقدم مع حسابك.", workspaceDesc: "اربط الطلبات والمهام والمستندات الخاصة.", openWorkspace: "فتح مساحة العمل" },
    discovery: { eyebrow: "اكتشاف البرامج", title: "ابحث عن الخيارات ثم انقلها إلى مساحة عملك", subtitle: "استخدم البيانات للاستكشاف، واعتمد المصدر الرسمي للمؤسسة للبرامج وشروط القبول والرسوم الدقيقة." },
    life: { badge: "الحياة في الخارج", title: "حياة الطالب دون تشتيت المسار الأساسي", subtitle: "المجتمع والسوق وحدات مساندة تكمل رحلة التعليم ولا تستبدلها.", workspace: "الذهاب إلى مساحة العمل", groups: [ { title: "السكن", description: "قيّم السكن والغرف وزملاء السكن بأمان أكبر.", items: ["سكن طلابي", "منزل / غرفة", "زميل سكن"] }, { title: "المال والعمل", description: "أدر المنح والعمل الطلابي والميزانية في مكان واحد.", items: ["منح", "عمل وتدريب", "تمويل"] }, { title: "المجتمع", description: "شبكات طلابية خاضعة للإشراف حسب المدينة والمؤسسة والبرنامج.", items: ["مجتمعات", "مجموعات طلاب", "روابط محلية"] }, { title: "الحياة اليومية", description: "الصحة والنقل والاتصال والسوق كأدوات مساندة.", items: ["صحة", "نقل", "اتصال وسوق"] } ], institution: "بيانات المؤسسة", institutionDesc: "يتم فصل المصادر الرسمية عن الإشارات الأكاديمية.", moderation: "إعلانات المجتمع", moderationDesc: "حالة الإشراف والتحقق تبقى واضحة.", privateFiles: "ملفات خاصة", privateFilesDesc: "لا تتم مشاركة مستندات التقديم عبر رابط عام." },
    commerce: { badge: "حالة الدفع الآمن", title: "محتوى البوابة متاح والمدفوعات متوقفة بأمان", description: "الإنتاج يعمل على استضافة ثابتة، لذلك لا تبدأ مدفوعات البطاقات أو حسابات التحويل هنا، ولا تنتقل أي مفاتيح سرية إلى المتصفح.", contact: "الاستفسار عن العضوية والدفع", plans: "خطط العضوية", plansTitle: "راجع الخطة المناسبة لرحلتك", plansDesc: "الخطط وحزم الرصيد واضحة؛ سيتم تفعيل الشراء مع backend الدفع الآمن.", featured: "الأكثر اختياراً", month: "شهر", year: "سنة", creditsIncluded: "رصيد مشمول", securePending: "الدفع الآمن قيد الإعداد", creditPacks: "رصيد الإعلانات", compareCredits: "مقارنة حزم الرصيد", purchaseSoon: "الشراء قريباً", planDescriptions: { basic: "أدوات البوابة الأساسية والتحقق.", plus: "تخطيط أوسع للطلبات والاستقرار.", pro: "أدوات متقدمة للاستخدام المكثف." }, planFeatures: { basic: ["دخول البوابة", "10 أرصدة بداية", "اكتشاف البرامج والمؤسسات", "العناصر المحفوظة", "طلب التحقق"], plus: ["كل Basic", "30 رصيداً", "مخطط المواعيد والمستندات", "مجتمعات موثقة", "إشعارات مخصصة"], pro: ["كل Plus", "80 رصيداً", "مطابقة متقدمة", "مساحة مستندات خاصة", "إشراف ذو أولوية"] } },
  },
  ru: {
    hero: { title: "Ваш путь к учёбе за рубежом,", accent: "в одном рабочем пространстве.", subtitle: "Управляйте поиском программ, заявками, приватными документами, визой, жильём и прибытием в одном кабинете.", discover: "Найти программы", continue: "Продолжить путь", privateDocs: "Приватные документы", officialSources: "Официальные источники отдельно", deadlines: "Работа с дедлайнами", overview: "Обзор пути", overviewTitle: "Сначала следующий шаг, затем детали", nextAction: "Следующее важное действие", nextActionTitle: "Добавьте первые целевые вузы", nextActionDesc: "Портал показывает действие, которое продвигает вас вперёд, вместо всех меню одновременно.", applications: "Заявки", documents: "Документы", life: "Студенческая жизнь", provenance: "Тип источника и актуальность видимы" },
    journey: { badge: "Путь студента", title: "Управляйте всем путём, а не только заявкой", subtitle: "Этапы связаны: документы, дедлайны, заявки, виза, жильё и прибытие.", descriptions: { discover: "Сравнивайте страны, города, вузы и направления.", shortlist: "Сохраняйте действительно важные варианты.", documents: "Организуйте файлы заявки в приватном центре.", apply: "Отслеживайте сроки, статус и недостающие требования.", offer: "Следите за офферами и решениями.", visa: "Планируйте визу, финансы и официальные шаги.", housing: "Безопаснее оценивайте жильё и переезд.", arrival: "Завершайте задачи прибытия и первой недели." }, workspaceTitle: "Рабочее пространство развивается вместе с аккаунтом.", workspaceDesc: "Свяжите заявки, задачи и приватные документы.", openWorkspace: "Открыть workspace" },
    discovery: { eyebrow: "Поиск программ", title: "Найдите варианты и перенесите их в workspace", subtitle: "Используйте данные для поиска; точные программы, требования и цены проверяйте на официальном сайте учреждения." },
    life: { badge: "Жизнь за рубежом", title: "Студенческая жизнь без помех основному процессу", subtitle: "Сообщество и маркетплейс — вспомогательные модули образовательного пути.", workspace: "В workspace", groups: [ { title: "Жильё", description: "Безопаснее оценивайте общежития, комнаты и соседей.", items: ["Общежития", "Дом / комната", "Соседи"] }, { title: "Финансы & работа", description: "Стипендии, работа и бюджет в одном месте.", items: ["Стипендии", "Работа & стажировки", "Финансы"] }, { title: "Сообщество", description: "Модерируемые сети по городу, вузу и программе.", items: ["Сообщества", "Студенческие группы", "Местные контакты"] }, { title: "Повседневность", description: "Здоровье, транспорт, связь и вторичный рынок как поддержка.", items: ["Здоровье", "Транспорт", "Связь & рынок"] } ], institution: "Данные вуза", institutionDesc: "Официальные источники и академические сигналы разделены.", moderation: "Объявления сообщества", moderationDesc: "Модерация и верификация остаются видимыми.", privateFiles: "Приватные файлы", privateFilesDesc: "Документы заявки не публикуются по открытой ссылке." },
    commerce: { badge: "Статус безопасной оплаты", title: "Портал доступен, платежи безопасно приостановлены", description: "Production размещён статически, поэтому платежи и payout-аккаунты здесь не запускаются, а секретные ключи не попадают в браузер.", contact: "Узнать об оплате и подписке", plans: "Тарифы", plansTitle: "Выберите подходящий тариф", plansDesc: "Тарифы и кредиты прозрачны; покупка включится после запуска безопасного backend.", featured: "Популярный", month: "месяц", year: "год", creditsIncluded: "кредитов включено", securePending: "Безопасная оплата готовится", creditPacks: "Кредиты объявлений", compareCredits: "Сравнить пакеты", purchaseSoon: "Покупка скоро", planDescriptions: { basic: "Базовые инструменты портала и верификация.", plus: "Больше инструментов для заявок и переезда.", pro: "Продвинутые инструменты для активных пользователей." }, planFeatures: { basic: ["Доступ к порталу", "10 стартовых кредитов", "Поиск программ", "Сохранённое", "Верификация"], plus: ["Всё Basic", "30 кредитов", "Планировщик дедлайнов и документов", "Проверенные сообщества", "Персональные уведомления"], pro: ["Всё Plus", "80 кредитов", "Расширенный matching", "Приватный центр документов", "Приоритетная модерация"] } },
  },
  zh: {
    hero: { title: "你的留学旅程，", accent: "集中在一个工作区。", subtitle: "在同一个学生工作区管理项目搜索、申请、私人文件、签证、住宿和抵达计划。", discover: "发现项目", continue: "继续我的旅程", privateDocs: "私人学生文件", officialSources: "区分官方来源", deadlines: "以截止日期为中心", overview: "旅程概览", overviewTitle: "先看到下一步，再深入细节", nextAction: "下一项重要行动", nextActionTitle: "把第一批目标院校加入候选清单", nextActionDesc: "门户优先展示真正推动进度的行动，而不是一次展示所有菜单。", applications: "申请", documents: "文件", life: "学生生活", provenance: "来源类型与更新时间始终可见" },
    journey: { badge: "学生旅程", title: "管理完整旅程，而不只是申请", subtitle: "每个阶段彼此连接：文件、截止日期、申请、签证、住宿和抵达。", descriptions: { discover: "比较国家、城市、院校和学术领域。", shortlist: "集中保存真正值得评估的选项。", documents: "在私人文件中心整理申请材料。", apply: "跟踪截止日期、状态和缺失要求。", offer: "跟踪录取与决策。", visa: "规划签证、资金和官方手续。", housing: "更安全地评估住宿和安置选项。", arrival: "完成抵达和第一周任务。" }, workspaceTitle: "工作区会随着你的账户持续推进。", workspaceDesc: "把申请、任务和私人文件连接在一起。", openWorkspace: "打开工作区" },
    discovery: { eyebrow: "项目发现", title: "先找到选项，再放进你的工作区", subtitle: "院校和学术数据用于探索；准确的项目、录取要求和费用请以院校官方来源为准。" },
    life: { badge: "海外生活", title: "学生生活模块不会打乱核心流程", subtitle: "社区和市场是补充教育旅程的辅助模块，而不是核心产品。", workspace: "进入工作区", groups: [ { title: "住宿", description: "更安全地评估宿舍、住房、房间和室友。", items: ["宿舍", "住房 / 房间", "室友"] }, { title: "资金与工作", description: "统一管理奖学金、学生工作和日常预算。", items: ["奖学金", "工作与实习", "资金"] }, { title: "社区", description: "按城市、院校和项目访问经过管理的学生网络。", items: ["社区", "学生群组", "本地联系"] }, { title: "日常生活", description: "把健康、交通、通信和二手市场作为辅助工具。", items: ["健康", "交通", "通信与市场"] } ], institution: "院校数据", institutionDesc: "官方来源与学术信号分别标注。", moderation: "社区发布", moderationDesc: "审核和账户认证状态保持可见。", privateFiles: "私人文件", privateFilesDesc: "申请文件不会通过公开链接共享。" },
    commerce: { badge: "安全支付状态", title: "门户内容可用，支付已安全暂停", description: "生产站点采用静态托管，因此不会在浏览器中启动银行卡支付或收款账户操作，也不会暴露任何密钥。", contact: "咨询会员与支付", plans: "会员计划", plansTitle: "查看适合你的计划", plansDesc: "计划与积分透明展示；安全支付 backend 上线后才会启用购买。", featured: "最受欢迎", month: "月", year: "年", creditsIncluded: "积分已包含", securePending: "安全支付准备中", creditPacks: "发布积分", compareCredits: "比较积分包", purchaseSoon: "购买即将开放", planDescriptions: { basic: "核心门户与认证工具。", plus: "更多申请与安置规划工具。", pro: "面向高频用户的高级工具。" }, planFeatures: { basic: ["门户访问", "10 初始积分", "院校与项目发现", "收藏", "认证申请"], plus: ["Basic 全部功能", "30 积分", "截止日期与文件规划", "认证社区", "个性化通知"], pro: ["Plus 全部功能", "80 积分", "高级项目匹配", "私人文件工作区", "优先审核"] } },
  },
};

export function usePortalPublicCopy() {
  const { i18n } = useTranslation();
  const raw = i18n.resolvedLanguage || i18n.language || "tr";
  const normalized = raw.split("-")[0] as LanguageCode;
  const language: LanguageCode = normalized in COPY ? normalized : "tr";
  return COPY[language];
}
