import { useTranslation } from "react-i18next";

import type { LanguageCode } from "@/i18n";

type VerifyCopy = {
  back: string;
  eyebrow: string;
  title: string;
  subtitle: string;
  name: string;
  namePlaceholder: string;
  role: string;
  roles: { student: string; advertiser: string; institution: string };
  documentType: string;
  documentTypes: {
    student_document: string;
    identity_document: string;
    company_document: string;
    dormitory_license: string;
  };
  catalogNote: string;
  uploadTitle: string;
  uploadHint: string;
  privacy: string;
  submit: string;
  submittedTitle: string;
  submittedDesc: string;
  success: string;
  invalidName: string;
  invalidFile: string;
  sessionMissing: string;
  submitError: string;
};

const COPY: Record<LanguageCode, VerifyCopy> = {
  tr: { back: "Student Journey’e dön", eyebrow: "Güvenli hesap doğrulama", title: "Hesabını doğrula", subtitle: "İlan ve topluluk güvenliği için öğrenci, ilan veren veya kurum kimliğini manuel inceleme kuyruğuna gönder.", name: "Ad soyad / kurum adı", namePlaceholder: "Profilde görünecek ad", role: "Hesap türü", roles: { student: "Öğrenci", advertiser: "İlan veren kişi", institution: "Kurum / yurt / işletme" }, documentType: "Belge türü", documentTypes: { student_document: "Öğrenci belgesi", identity_document: "Kimlik belgesi", company_document: "Şirket / kurum yetki belgesi", dormitory_license: "Yurt / işletme ruhsatı" }, catalogNote: "Kurum ve program bilgileri profil eşleştirmesi için kullanılır; resmî kabul bilgisi olarak gösterilmez.", uploadTitle: "Belgeyi güvenli alana yükle", uploadHint: "PDF, JPG veya PNG · en fazla 8 MB", privacy: "Belge private storage alanında tutulur ve yalnız yetkili inceleme akışında erişilir; herkese açık URL oluşturulmaz.", submit: "Doğrulama başvurusu gönder", submittedTitle: "Başvuru alındı", submittedDesc: "Belgen herkese açık değildir. İnceleme sonucu hesap durumunda gösterilir.", success: "Doğrulama başvurunuz güvenli inceleme kuyruğuna alındı.", invalidName: "Lütfen adınızı veya kurum adını yazın.", invalidFile: "PDF, JPG veya PNG biçiminde en fazla 8 MB belge seçin.", sessionMissing: "Oturum bulunamadı.", submitError: "Doğrulama başvurusu gönderilemedi." },
  en: { back: "Back to Student Journey", eyebrow: "Secure account verification", title: "Verify your account", subtitle: "Submit your student, seller or institution identity for manual review to improve marketplace and community safety.", name: "Name / institution", namePlaceholder: "Name shown on your profile", role: "Account type", roles: { student: "Student", advertiser: "Seller / advertiser", institution: "Institution / dorm / business" }, documentType: "Document type", documentTypes: { student_document: "Student document", identity_document: "Identity document", company_document: "Company / authorization document", dormitory_license: "Dorm / business licence" }, catalogNote: "Institution and program details are used for profile matching and are not presented as official admission information.", uploadTitle: "Upload to secure storage", uploadHint: "PDF, JPG or PNG · up to 8 MB", privacy: "The file stays in private storage and is accessible only through the authorized review flow; no public URL is created.", submit: "Submit verification", submittedTitle: "Submission received", submittedDesc: "Your document is not public. The review result will appear in your account status.", success: "Your verification request was added to the secure review queue.", invalidName: "Enter your name or institution name.", invalidFile: "Select a PDF, JPG or PNG file up to 8 MB.", sessionMissing: "Session not found.", submitError: "Verification request could not be submitted." },
  de: { back: "Zurück zur Student Journey", eyebrow: "Sichere Kontoverifizierung", title: "Konto verifizieren", subtitle: "Reiche deinen Studenten-, Anbieter- oder Institutionsnachweis zur manuellen Prüfung ein.", name: "Name / Institution", namePlaceholder: "Name im Profil", role: "Kontotyp", roles: { student: "Student/in", advertiser: "Anbieter/in", institution: "Institution / Wohnheim / Betrieb" }, documentType: "Dokumenttyp", documentTypes: { student_document: "Studierendennachweis", identity_document: "Identitätsnachweis", company_document: "Unternehmens-/Vollmachtsnachweis", dormitory_license: "Wohnheim-/Betriebslizenz" }, catalogNote: "Institution und Programm dienen der Profilzuordnung und werden nicht als offizielle Zulassungsinformation dargestellt.", uploadTitle: "Sicher hochladen", uploadHint: "PDF, JPG oder PNG · bis 8 MB", privacy: "Die Datei bleibt privat und ist nur im autorisierten Prüfprozess zugänglich; es wird keine öffentliche URL erstellt.", submit: "Verifizierung senden", submittedTitle: "Antrag erhalten", submittedDesc: "Dein Dokument ist nicht öffentlich. Das Prüfergebnis erscheint im Kontostatus.", success: "Verifizierung wurde sicher zur Prüfung eingereicht.", invalidName: "Name oder Institution eingeben.", invalidFile: "PDF, JPG oder PNG bis 8 MB auswählen.", sessionMissing: "Sitzung nicht gefunden.", submitError: "Verifizierung konnte nicht gesendet werden." },
  fr: { back: "Retour au parcours", eyebrow: "Vérification sécurisée du compte", title: "Vérifier votre compte", subtitle: "Soumettez votre justificatif étudiant, vendeur ou établissement à une vérification manuelle.", name: "Nom / établissement", namePlaceholder: "Nom affiché sur le profil", role: "Type de compte", roles: { student: "Étudiant", advertiser: "Vendeur / annonceur", institution: "Établissement / résidence / entreprise" }, documentType: "Type de document", documentTypes: { student_document: "Justificatif étudiant", identity_document: "Pièce d’identité", company_document: "Document société / habilitation", dormitory_license: "Licence résidence / activité" }, catalogNote: "Les informations d’établissement et de programme servent au rapprochement du profil et ne constituent pas une information officielle d’admission.", uploadTitle: "Téléverser dans l’espace sécurisé", uploadHint: "PDF, JPG ou PNG · 8 Mo max.", privacy: "Le fichier reste privé et n’est accessible que dans le flux de vérification autorisé; aucune URL publique n’est créée.", submit: "Envoyer la vérification", submittedTitle: "Demande reçue", submittedDesc: "Votre document n’est pas public. Le résultat apparaîtra dans le statut du compte.", success: "Votre demande a été ajoutée à la file de vérification sécurisée.", invalidName: "Saisissez votre nom ou celui de l’établissement.", invalidFile: "Choisissez un PDF, JPG ou PNG de 8 Mo maximum.", sessionMissing: "Session introuvable.", submitError: "Impossible d’envoyer la demande de vérification." },
  it: { back: "Torna a Student Journey", eyebrow: "Verifica account sicura", title: "Verifica il tuo account", subtitle: "Invia il documento di studente, venditore o istituzione alla revisione manuale.", name: "Nome / istituzione", namePlaceholder: "Nome mostrato nel profilo", role: "Tipo di account", roles: { student: "Studente", advertiser: "Venditore / inserzionista", institution: "Istituzione / studentato / attività" }, documentType: "Tipo di documento", documentTypes: { student_document: "Documento studente", identity_document: "Documento d’identità", company_document: "Documento azienda / autorizzazione", dormitory_license: "Licenza studentato / attività" }, catalogNote: "I dati di istituzione e programma servono ad abbinare il profilo e non sono informazioni ufficiali di ammissione.", uploadTitle: "Carica nello spazio sicuro", uploadHint: "PDF, JPG o PNG · max 8 MB", privacy: "Il file rimane privato ed è accessibile solo nel flusso di revisione autorizzato; non viene creato alcun URL pubblico.", submit: "Invia verifica", submittedTitle: "Richiesta ricevuta", submittedDesc: "Il documento non è pubblico. L’esito apparirà nello stato dell’account.", success: "Richiesta aggiunta alla coda di revisione sicura.", invalidName: "Inserisci il nome o l’istituzione.", invalidFile: "Seleziona PDF, JPG o PNG fino a 8 MB.", sessionMissing: "Sessione non trovata.", submitError: "Impossibile inviare la verifica." },
  es: { back: "Volver a Student Journey", eyebrow: "Verificación segura de cuenta", title: "Verifica tu cuenta", subtitle: "Envía tu identificación de estudiante, anunciante o institución a revisión manual.", name: "Nombre / institución", namePlaceholder: "Nombre visible en el perfil", role: "Tipo de cuenta", roles: { student: "Estudiante", advertiser: "Vendedor / anunciante", institution: "Institución / residencia / empresa" }, documentType: "Tipo de documento", documentTypes: { student_document: "Documento de estudiante", identity_document: "Documento de identidad", company_document: "Documento de empresa / autorización", dormitory_license: "Licencia de residencia / negocio" }, catalogNote: "Los datos de institución y programa se usan para asociar el perfil y no se muestran como información oficial de admisión.", uploadTitle: "Subir al espacio seguro", uploadHint: "PDF, JPG o PNG · máximo 8 MB", privacy: "El archivo permanece privado y solo se accede desde el flujo de revisión autorizado; no se crea una URL pública.", submit: "Enviar verificación", submittedTitle: "Solicitud recibida", submittedDesc: "Tu documento no es público. El resultado aparecerá en el estado de la cuenta.", success: "Solicitud añadida a la cola de revisión segura.", invalidName: "Introduce tu nombre o institución.", invalidFile: "Selecciona PDF, JPG o PNG de hasta 8 MB.", sessionMissing: "Sesión no encontrada.", submitError: "No se pudo enviar la verificación." },
  ar: { back: "العودة إلى رحلة الطالب", eyebrow: "تحقق آمن من الحساب", title: "تحقق من حسابك", subtitle: "أرسل إثبات الطالب أو المعلن أو المؤسسة للمراجعة اليدوية لتعزيز أمان المجتمع والسوق.", name: "الاسم / المؤسسة", namePlaceholder: "الاسم الظاهر في الملف", role: "نوع الحساب", roles: { student: "طالب", advertiser: "بائع / معلن", institution: "مؤسسة / سكن / نشاط" }, documentType: "نوع المستند", documentTypes: { student_document: "إثبات طالب", identity_document: "وثيقة هوية", company_document: "وثيقة شركة / تفويض", dormitory_license: "ترخيص سكن / نشاط" }, catalogNote: "تُستخدم معلومات المؤسسة والبرنامج لمطابقة الملف ولا تُعرض كمعلومات قبول رسمية.", uploadTitle: "ارفع إلى المساحة الآمنة", uploadHint: "PDF أو JPG أو PNG · حتى 8 ميغابايت", privacy: "يبقى الملف في تخزين خاص ولا يمكن الوصول إليه إلا ضمن مسار المراجعة المصرح؛ لا يتم إنشاء رابط عام.", submit: "إرسال طلب التحقق", submittedTitle: "تم استلام الطلب", submittedDesc: "المستند غير عام. ستظهر نتيجة المراجعة في حالة الحساب.", success: "تمت إضافة طلب التحقق إلى قائمة المراجعة الآمنة.", invalidName: "أدخل اسمك أو اسم المؤسسة.", invalidFile: "اختر PDF أو JPG أو PNG بحجم لا يتجاوز 8 ميغابايت.", sessionMissing: "لم يتم العثور على جلسة.", submitError: "تعذر إرسال طلب التحقق." },
  ru: { back: "Назад к Student Journey", eyebrow: "Безопасная верификация аккаунта", title: "Подтвердите аккаунт", subtitle: "Отправьте подтверждение студента, продавца или организации на ручную проверку.", name: "Имя / организация", namePlaceholder: "Имя в профиле", role: "Тип аккаунта", roles: { student: "Студент", advertiser: "Продавец / автор объявления", institution: "Организация / общежитие / бизнес" }, documentType: "Тип документа", documentTypes: { student_document: "Студенческий документ", identity_document: "Документ личности", company_document: "Документ компании / полномочий", dormitory_license: "Лицензия общежития / бизнеса" }, catalogNote: "Данные об организации и программе используются для профиля и не считаются официальной информацией о поступлении.", uploadTitle: "Безопасно загрузить", uploadHint: "PDF, JPG или PNG · до 8 МБ", privacy: "Файл остаётся приватным и доступен только в авторизованном процессе проверки; публичная ссылка не создаётся.", submit: "Отправить на проверку", submittedTitle: "Заявка получена", submittedDesc: "Документ не публикуется. Результат появится в статусе аккаунта.", success: "Заявка добавлена в безопасную очередь проверки.", invalidName: "Введите имя или организацию.", invalidFile: "Выберите PDF, JPG или PNG до 8 МБ.", sessionMissing: "Сессия не найдена.", submitError: "Не удалось отправить заявку." },
  zh: { back: "返回 Student Journey", eyebrow: "安全账户认证", title: "认证你的账户", subtitle: "提交学生、卖家或机构身份材料进行人工审核，以提升社区和市场安全。", name: "姓名 / 机构", namePlaceholder: "资料中显示的名称", role: "账户类型", roles: { student: "学生", advertiser: "卖家 / 发布者", institution: "机构 / 宿舍 / 企业" }, documentType: "文件类型", documentTypes: { student_document: "学生证明", identity_document: "身份证明", company_document: "公司 / 授权文件", dormitory_license: "宿舍 / 营业许可" }, catalogNote: "院校与项目信息仅用于资料匹配，不作为官方录取信息。", uploadTitle: "上传到安全空间", uploadHint: "PDF、JPG 或 PNG · 最大 8 MB", privacy: "文件保存在私人存储中，仅可通过授权审核流程访问，不会生成公开链接。", submit: "提交认证", submittedTitle: "已收到申请", submittedDesc: "文件不会公开。审核结果会显示在账户状态中。", success: "认证申请已进入安全审核队列。", invalidName: "请输入姓名或机构名称。", invalidFile: "请选择不超过 8 MB 的 PDF、JPG 或 PNG。", sessionMissing: "未找到会话。", submitError: "无法提交认证申请。" },
};

export function usePortalVerifyCopy() {
  const { i18n } = useTranslation();
  const raw = i18n.resolvedLanguage || i18n.language || "tr";
  const normalized = raw.split("-")[0] as LanguageCode;
  const language: LanguageCode = normalized in COPY ? normalized : "tr";
  return COPY[language];
}
