apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cliniga-ai-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cliniga-ai-secret-store
    kind: ClusterSecretStore
  target:
    name: cliniga-ai-secrets
    creationPolicy: Owner
  data:
    - secretKey: database_url
      remoteRef:
        key: cliniga-ai/database-url
    - secretKey: redis_url
      remoteRef:
        key: cliniga-ai/redis-url
    - secretKey: hf_token
      remoteRef:
        key: cliniga-ai/huggingface-token
