{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cliniga-ai.serviceAccountName" . }}
  labels:
    {{- include "cliniga-ai.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
