apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: cliniga-ai-pod-kill
  namespace: cliniga-ai
spec:
  action: pod-kill
  mode: one
  selector:
    namespaces:
      - cliniga-ai
    labelSelectors:
      app: cliniga-ai
  duration: '30s'
  scheduler:
    cron: '@every 24h'
